name: Build and Push Docker Image

on:
  push:
    branches:
      - snh-gcpbuild  # Trigger on pushes to the main branch
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Google Cloud authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configure Docker to use the Google Cloud Artifact Registry
      - name: Set up Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/bold-apricot-453614-f7/cloud-run-source-deploy/discovery-week-group-3-endangered-species/endangered-species:fd47282b78295785113c398120710e6bf49520cd .

      # Push the Docker image to the Artifact Registry
      - name: Push Docker image
        run: |
          docker push europe-west1-docker.pkg.dev/bold-apricot-453614-f7/cloud-run-source-deploy/discovery-week-group-3-endangered-species/endangered-species:fd47282b78295785113c398120710e6bf49520cd
